[Params.style.vars]
fontMono = "'Georgia', 'Georgia', 'Times New Roman'"
bodyFontSize = "1.1rem"
fontSans = "'Poppins', 'Open Sans', 'Helvetica', 'Arial', 'sans-serif'"
dimboxBackground = "#dee7ff"
headerColor = "#c5050c"
logoColor = "#c5050c"
menuListColor = "#c5050c"
hoverTextColor = "white"
taglineColor = "#4a4a4a"
hoverMenuUnderline = "no"

[Params.style.vars.old]
sidebarLinkUnderline = "underline"